'THIS IS  CREATED BY B.SUJAY
'THE BUGS OF WRONG INGEGERS SHOWING FIXED IN THIS VERSION
'DO NOT PRODUCE THIS AS YOURS
'IF YOU USE INTEGERS IT WILL USE ABSOLUTE VALUES ONLY
Cls
Dim A As Integer
Dim B As Integer
Dim C As Integer
Input "ENTER THE FIRST NUMBER"; A
Input "ENTER THE SECOND NUMBER"; B
Input "ENTER THE SECOND NUMBER"; C
If A > B And A > C Then
    Print "THE GREATEST NUMBER IS"; A
ElseIf B > A And B > C Then
    Print "THE GREATEST NUMBER IS"; B
Else
    Print "THE GREATEST NUMBER IS"; C
End If
End
